language: python
python:
  - 3.6

os:
  - linux
  - osx

compiler: clang
osx_image: xcode8.2

install:
  - travis_retry pip install --upgrade pip setuptools wheel
  - travis_retry pip install -r requirements.txt --only-binary=scipy
  - python setup.py install

script:
    - ./tests/run_tests.sh