language: python

cache:
    - directories:
        - ${TRAVIS_BUILD_DIR}/itkjunk/
        - ${TRAVIS_BUILD_DIR}/itkjunk/itkbuild-linux
        - ${TRAVIS_BUILD_DIR}/itkjunk/itkbuild-osx
        - /usr/local


jobs:
  include:

#    - stage: makeVTK
#      script: |
#        unset CCACHE_DISABLE
#        export CCACHE_DIR=$HOME/.ccache
#        ./scripts/configure_VTK_External_linux.sh;
#        export VTK_DIR=$TRAVIS_BUILD_DIR/vtkbuild-linux;
#      os: linux
#      sudo: required
#      python: 3.6
#    - stage: makeVTK
#      script: |
#        brew update;
#        brew install ccache;
#        unset CCACHE_DISABLE;
#        export CCACHE_DIR=$HOME/.ccache;
#        ccache --show-stats;
#        export PATH="/usr/local/opt/ccache/libexec:$PATH";
#        ./scripts/configure_VTK_External_mac.sh;
#        export VTK_DIR=$TRAVIS_BUILD_DIR/vtkbuild-mac;
#      os: osx
#      sudo: required
#      language: generic

    - stage: makeITK
      script: |
        unset CCACHE_DISABLE
        export CCACHE_DIR=$HOME/.ccache
        export VTK_DIR=$TRAVIS_BUILD_DIR/vtkbuild-linux;
        CMAKE_INSTALLER=install-cmake.sh;
        curl -sSL https://cmake.org/files/v3.11/cmake-3.11.3-Linux-x86_64.sh -o ${CMAKE_INSTALLER};
        chmod +x ${CMAKE_INSTALLER};
        sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license;
        cmake --version;
        ./scripts/configure_ITK_External_linux.sh ;
        find /usr/local -name cmake
      os: linux
      sudo: required
      python: 3.6
    - stage: makeITK
      script: |
        brew update;
        brew install ccache;
        unset CCACHE_DISABLE;
        export CCACHE_DIR=$HOME/.ccache;
        ccache --show-stats;
        export PATH="/usr/local/opt/ccache/libexec:$PATH";
        export VTK_DIR=$TRAVIS_BUILD_DIR/vtkbuild-mac;
        brew install cmake;
        brew upgrade cmake;
        cmake --version;
        ./scripts/configure_ITK_External_linux.sh
      os: osx
      language: generic
      env: PIP=pip2
      python: 3.6
      sudo: required
      language: generic

    - stage: install
      script: |
        $PIP install cibuildwheel==0.9.1;
        cibuildwheel --output-dir wheelhouse;
        export ITK_DIR=${TRAVIS_BUILD_DIR}/itkjunk/itkbuild-${TRAVIS_OS_NAME};
        export VTK_DIR=$TRAVIS_BUILD_DIR/vtkbuild-linux;
        travis_retry pip install --upgrade pip setuptools wheel;
        travis_retry pip install -r requirements.txt --only-binary=scipy;
        travis_retry pip install coveralls plotly webcolors scikit-image;
        python setup.py install
        ./tests/run_tests_travis.sh
      os: linux
      python: 3.6
      sudo: required
    - stage: install
      script: |
        $PIP install cibuildwheel==0.9.1;
        cibuildwheel --output-dir wheelhouse;
        export ITK_DIR=${TRAVIS_BUILD_DIR}/itkjunk/itkbuild-${TRAVIS_OS_NAME};
        python -m pip install --upgrade pip;
        pip install --upgrade wheel;
        pip install --upgrade numpy;
        pip install --upgrade setuptools;
        alias cmake=/usr/local/bin/cmake;
        export VTK_DIR=$HOME/vtkbuild-mac;
        travis_retry pip install --upgrade pip setuptools wheel;
        travis_retry pip install -r requirements.txt --only-binary=scipy;
        travis_retry pip install coveralls coverage plotly webcolors scikit-image;
        python setup.py install;
        ./tests/run_tests_travis.sh
      os: osx
      env: PIP=pip2
      python: 3.6
      sudo: required
      language: generic

    - stage: "Deployment"
      if: tag IS present
      script:
        - travis_wait 100 R CMD INSTALL --debug --build ${PROJ_DIR};
      deploy:
        provider: releases
        api_key:
          secure: VevZHK5WDwd2mFSrF3+b2jTRzImb6juOgewcOvZ8LJ2S70khn64Kx4+JGUvk5miKWVbKnHIhPxOJY50muO9sT15ApP+HFZYpiVpx4l/hEypk9zmJD+f+ERuN7j8elCzUZqet3v77XD+pBcYMxFARew4gGDkG2LO5casij0YNiyQ=
        file_glob: true
        file: ${PROJ_DIR}*.t*gz
        skip_cleanup: true
        overwrite: true
        on:
          repo: ANTsX/ANTsPy
          tags: true
          all_branches: true
      os: linux
    - stage: "Deployment"
      if: tag IS present
      script:
        - travis_wait 100 R CMD INSTALL --debug --build ${PROJ_DIR};
      deploy:
        provider: releases
        api_key:
          secure: VevZHK5WDwd2mFSrF3+b2jTRzImb6juOgewcOvZ8LJ2S70khn64Kx4+JGUvk5miKWVbKnHIhPxOJY50muO9sT15ApP+HFZYpiVpx4l/hEypk9zmJD+f+ERuN7j8elCzUZqet3v77XD+pBcYMxFARew4gGDkG2LO5casij0YNiyQ=
        file_glob: true
        file: *ANTsPy*whl
        skip_cleanup: true
        overwrite: true
        on:
          repo: ANTsX/ANTsPy
          tags: true
          all_branches: true
      os: osx

  allow_failures:
    - os: osx

branches:
  only:
    - master
