language: python
python:
  - 3.6

os:
  - linux
  - osx

compiler: clang

install:
  - travis_retry pip install --upgrade pip setuptools wheel
  - travis_retry pip install -r requirements.txt --only-binary=scipy
  - python setup.py install

notifications:
  email:
    recipients:
    - nickmarch31@yahoo.com
    on_success: change
    on_failure: always
