language: python


cache:
    - ccache
    - directories:
        - $HOME/.ccache
        - $HOME/itkbuild



before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; 
    then
      brew update;
      brew install ccache;
      unset CCACHE_DISABLE;
      export CCACHE_DIR=$HOME/.ccache;
      ccache --show-stats;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
      
      brew install python3;
      python3 -m venv venv;
      source venv/bin/activate;
  fi

# Manually install python on osx
#install: |
#  travis_retry pip install --upgrade pip setuptools wheel
#  travis_retry pip install -r requirements.txt --only-binary=scipy
#  python setup.py install

jobs:
  include:

    - stage: makeITK
      script: |
        if [[ ! -d $HOME/itkbuild ]];
          then
            ./configure_ITK_External.sh;
            export ITK_DIR=~/itkbuild/itkbuild;
          fi
      os: linux
      python: 3.6
    - stage: makeITK
      script: |
        brew update;
        brew install ccache;
        unset CCACHE_DISABLE;
        export CCACHE_DIR=$HOME/.ccache;
        ccache --show-stats;
        if [[ ! -d $HOME/itkbuild ]];
        then
          ./configure_ITK_External.sh;
          export ITK_DIR=~/itkbuild/itkbuild;
        fi
      os: osx
      sudo: required
      language: generic

    - stage: install
      script: |
        export ITK_DIR=$HOME/itkbuild/itkbuild
        travis_retry pip install --upgrade pip setuptools wheel
        travis_retry pip install -r requirements.txt --only-binary=scipy
        python setup.py install
      os: linux
      python: 3.6
    - stage: install
      script: |
        export ITK_DIR=$HOME/itkbuild/itkbuild
        travis_retry pip install --upgrade pip setuptools wheel
        travis_retry pip install -r requirements.txt --only-binary=scipy
        python setup.py install
      os: osx
      sudo: required
      language: generic

    - stage: test
      script:
        - ./tests/run_test.sh
      os: osx
      sudo: required
      language: generic
    - stage: test
      script:
        - ./tests/run_test.sh
      os: linux
      python: 3.6

  allow_failures:
    - os: osx


#script:
#   - ./tests/run_tests.sh

branches:
  only:
    - master

