language: python
python:
  - "3.6"

cache:
    - directories:
        - ${TRAVIS_BUILD_DIR}/itkbuild
        - /usr/local


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      CMAKE_INSTALLER=install-cmake.sh && \
        curl -sSL https://cmake.org/files/v3.11/cmake-3.11.3-Linux-x86_64.sh -o ${CMAKE_INSTALLER} && \
        chmod +x ${CMAKE_INSTALLER} && \
        sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license
    fi
  - alias cmake=/usr/local/bin/cmake
  - export PATH=/usr/local/bin/cmake/bin:/usr/local/bin:${PATH}
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      echo "need cmake 3.12" && \
        brew update && \
        brew install ccache && \
        brew upgrade cmake && \
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
  - pip3 install scipy pandas numpy matplotlib
  - pip3 install coveralls plotly webcolors scikit-image;

#  - pip install  --user -r cibuildwheel==0.9.1;
#  - pip3 install --upgrade pip setuptools wheel
#  - pip3 install -r requirements.txt

install:
  - echo "skip this"

jobs:
    - stage: install
      env: PIP=pip
      script: |
#        export ITK_DIR=${TRAVIS_BUILD_DIR}/itkbuild;
#        export VTK_DIR=$TRAVIS_BUILD_DIR/vtkbuild-linux;
#        echo "myITK is"; echo $ITK_DIR;
#        ls $ITK_DIR;
        python3 setup.py install;
        ./tests/run_tests_travis.sh
      os: linux
      python: 3.6
      sudo: required

    - stage: install
      env: PIP=pip
      script: |
        alias cmake=/usr/local/bin/cmake;
        python3 setup.py install;
        ./tests/run_tests_travis.sh
      os: osx
      python: 3.6
      sudo: required
      language: generic

  allow_failures:
    - os: osx

branches:
  only:
    - master
